# Docker Compose for VM-like testing environment
# This creates isolated test environments for different OS behaviors

version: '3.8'

services:
  windows-test:
    build:
      context: ../dist/DictionaryApp
      dockerfile: ../../testing/Dockerfile.windows-test
    volumes:
      - ../dist/DictionaryApp:/app:ro
      - ./results:/results
    environment:
      - DISPLAY=:0
      - WINEPREFIX=/wine
    ports:
      - "5900:5900"  # VNC
      - "8080:8080"  # Web interface
    stdin_open: true
    tty: true
    
  mac-test:
    build:
      context: ../dist/DictionaryApp  
      dockerfile: ../../testing/Dockerfile.mac-test
    volumes:
      - ../dist/DictionaryApp:/app:ro
      - ./results:/results
    environment:
      - DISPLAY=:0
    ports:
      - "5901:5900"  # VNC
    stdin_open: true
    tty: true